language: r

services:
  - docker

os:
  - linux

r:
  - oldrel
  - release
  - devel

install:
  - docker build -t zchas39/rstudio-server .
  - docker run -d -p 127.0.0.1:8787:8787 --name rs -e USER=test_user -e PASSWORD=pwd123 zchas39/rstudio-server

script:
  - docker ps | grep -q rs

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
